# Generated by Django 3.1.13 on 2023-09-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(default='False', max_length=200, verbose_name='Participant name')),
                ('points', models.IntegerField(verbose_name='Points')),
            ],
        ),
    ]
