# Generated by Django 3.1.13 on 2023-09-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardrows',
            options={'verbose_name': 'Dashboard row', 'verbose_name_plural': 'Dashboard rows'},
        ),
        migrations.AlterField(
            model_name='dashboardrows',
            name='participant_name',
            field=models.CharField(max_length=200, verbose_name='Participant name'),
        ),
    ]
