# Generated by Django 3.1.13 on 2023-09-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230911_1329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dashboardrows',
            table='dashboard_dashboardrows',
        ),
    ]
